### ISSUE TITLE
Ai command error

### ISSUE THREAD

**Issue by dwifuady** [dwifuady/AiKamu#7]
![image](https://github.com/dwifuady/AiKamu/assets/2110266/ace257d5-98f0-48da-895f-90cebb81ea25)

```csharp
System.InvalidOperationException: Cannot respond twice to the same interaction
   at Discord.WebSocket.SocketCommandBase.RespondAsync(String text, Embed[] embeds, Boolean isTTS, Boolean ephemeral, AllowedMentions allowedMentions, MessageComponent components, Embed embed, RequestOptions options)
   at AiKamu.Bot.BotService.SlashCommandHandler(SocketSlashCommand slashCommand) in /src/AiKamu/Bot/BotService.cs:line 141
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Comment by dwifuady** [comment]
fixed by #9 #10
